name: take_your_meds
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    intl: ^0.17.0
    google_fonts: ^3.0.1
    cupertino_icons: ^1.0.2
    flutter_riverpod: ^2.0.0-dev.9
    hive: ^2.2.1
    hive_flutter: ^1.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    hive_generator: ^1.1.3
    build_runner: ^2.1.11

flutter:
    uses-material-design: true
    generate: true

    assets:
        - ./assets/
